### ISSUE TITLE
Not working with tokio

### ISSUE THREAD

**Issue by DevSlashRichie** [thoo0224/webhook-rs#15]
When I try to execute the endpoint with Tokyo, it displays many Send errors.

https://gist.github.com/siendoricardo/95bda1a9dcef4eb296d4c6119aec4843

**Comment by BohdanQQ** [comment]
Hi, thank you for reporting this!

I was able to recreate a subset of the attached error using this snippet (wrapped example code):

```rust
  tokio::spawn((|| async move {
      client.send(|message| message
          .content("@everyone")
          .username("Thoo")
          .avatar_url(IMAGE_URL)
          .embed(|embed| embed
              .title("Webhook")
              .description("Hello, World!")
              .footer("Footer", Some(String::from(IMAGE_URL)))
              .image(IMAGE_URL)
              .thumbnail(IMAGE_URL)
              .author("Lmao#0001", Some(String::from(IMAGE_URL)), Some(String::from(IMAGE_URL)))
              .field("name", "value", false))).await
  })()).await?;
 ```

If your code context is different, can you please also include a representative snippet which causes these errors?
For now, I can suggest a temporary fix (without using Components/Buttons) in the form of using version `2.0.0`.

---
# For anyone willing to discuss the real fix
The error occurs due to the usage of `Rc<RefCell<T>>` for a message context (provides meaningful error messages when user inputs violate the Discord API limitations). `Rc` is not Send, that is it. 

I was able to "hotfix" this by replacing the `Rc<RefCell<T>>` by `Arc<Mutex<T>>` (and `lock().unwrap()`ing instead of mut borrowing). The tests are passing [on this branch](https://github.com/BohdanQQ/webhook-rs/tree/send-support) but I will take a look at this more carefully later as I am not sure that this is the only and, more importantly, best solution. Any ideas are welcome.

**Comment by DevSlashRichie** [comment]
Looks great for the way it is being implemented.

IMO, since the way we create a Message is in a builder pattern, we might want to run the checks when executing a `.build()`, method. That way we can remove the context variable. The build method would return a Result<Message, Error>.

Also, not sure if using borrowing lifetimes can solve this error.

**Comment by BohdanQQ** [comment]
Thanks for the input. (IMO) Currently, the `WebhookClient::send` method kind of serves as the `build` method you have mentioned. What could be done is, as you suggest, remove the context members entirely and write some sort of `DiscordApiCompatible` trait with a single function `check -> Result<(), E>` implemented for all necessary structs (starting with `Message` and ending with the `Button`) that would check the fields.
A `Message`'s implementation of this trait would recursively call this `check` on its `ActionRow`s, etc., down to individual concrete components, enforcing different rules along the way. The top-level `check` call would be inside the `WebhookClient::send` where the `message.first_error_message()` call is done.

Such a solution would still probably require a "context" (imagine a hash set for `custom_id` duplicates detection), but this one could be kept outside the structs as a local variable passed to the `check` function.  The advantage (if it all works) would be (at least I think :D) that the public-facing API would not change.

Will get back with a draft of this change or an admission of defeat ;).

**Comment by BohdanQQ** [comment]
[Quick draft with tests passing as well as the snippet above, heavily WIP] (https://github.com/BohdanQQ/webhook-rs/commit/bdf402def7360c60e8f02ea9a406c79b983098ba).

**Comment by BohdanQQ** [comment]
After some more refactoring (mainly because the changes rendered some parts of the code redundant), I have [this version](https://github.com/BohdanQQ/webhook-rs/tree/send-support-contex-reimpl). The changes made don't break the current public-facing API and fix this issue by getting rid of the `context` members. 

I'd like to make time for one more review and wait a bit in case someone comes up with improvements (or entirely different solution) before submitting PR.
